# Generated by Django 5.1.7 on 2025-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
