# Generated by Django 5.1.7 on 2025-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.CharField(default='Default Subject', max_length=255),
        ),
    ]
