# Generated by Django 5.1.7 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='q2fxPTCcecmMaqKmyTXPIbp5t3fZt0JC', editable=False, max_length=32, unique=True),
        ),
    ]
