# Generated by Django 5.1.7 on 2025-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='en6wRAuBxIQycGwV3snSIf55GC7S1Fft', editable=False, max_length=32, unique=True),
        ),
    ]
