# Generated by Django 5.1.7 on 2025-03-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2hCTRC4gozvIu8JkP6U9cd9y76HFpPAx', editable=False, max_length=32, unique=True),
        ),
    ]
