# Generated by Django 5.1.7 on 2025-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KdWQYRr3VdfXs1baKVTby7KtFH8uIe3x', editable=False, max_length=32, unique=True),
        ),
    ]
