# Generated by Django 5.1.7 on 2025-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3A6hQyPr5jQDUa7aQWjeaY4665aVx1bS', editable=False, max_length=32, unique=True),
        ),
    ]
