# Generated by Django 5.1.7 on 2025-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Jnfpy9Aspt7DSeBAPsvzQiwJ43jVm5fL', editable=False, max_length=32, unique=True),
        ),
    ]
