# Generated by Django 5.1.7 on 2025-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Y4JEWhGPjl0DiAjEDz82hVg7IEj6yu85', editable=False, max_length=32, unique=True),
        ),
    ]
