# Generated by Django 5.1.7 on 2025-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='MZhX9jKN7ypruZezR3iwr5jXAWR9n1aZ', editable=False, max_length=32, unique=True),
        ),
    ]
