# Generated by Django 5.1.7 on 2025-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0023_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WIfxI301cjnAeP3eaN8Tz79uPtmxLSdo', editable=False, max_length=32, unique=True),
        ),
    ]
