# Generated by Django 5.1.7 on 2025-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AUCELZ9Bh4XGG8Q53WCN8iSLfcJ9PzUP', editable=False, max_length=32, unique=True),
        ),
    ]
