# Generated by Django 5.1.7 on 2025-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4cvtjkBedEL6IorDYCvsxomICTTMSlGX', editable=False, max_length=32, unique=True),
        ),
    ]
