# Generated by Django 5.1.7 on 2025-04-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0031_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='j72yiJXjcU6ntp3Q31Lr13Kzph1h50lD', editable=False, max_length=32, unique=True),
        ),
    ]
