# Generated by Django 5.1.7 on 2025-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0034_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6604qXw5QdKGt8UsDWAYhLKL7DqFwIg1', editable=False, max_length=32, unique=True),
        ),
    ]
