# Generated by Django 5.1.7 on 2025-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='PfpE9Ed3fthNj7glNr2dQTrA8OfeQuUP', editable=False, max_length=32, unique=True),
        ),
    ]
