# Generated by Django 5.1.7 on 2025-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0039_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NH4tAEjTlOZFYuiZjtqvT34XA0usb5Mt', editable=False, max_length=32, unique=True),
        ),
    ]
